#!/usr/bin/env node
/**
 * web-clone / download.mjs — the separate download pass (R7), auth-aware (F4),
 * content-addressed (F5/F7).
 *
 * Runs AFTER orchestrator.mjs. Replays the crawl's storageState through
 * Playwright's APIRequestContext (cookies ride along — CDN assets behind the
 * login download fine), writes each file ONCE into a content-hash store, then
 * writes hash/localPath back into every route's media.json and regenerates the
 * global media-index.md (the AI-readable layer, R6).
 *
 * Usage (repo root):   node .claude/skills/web-clone/scripts/download.mjs
 *   --out <dir>        captures dir      default _webclone/captures
 *   --staging <dir>    hash store dir    default _webclone/staging
 *   --max-bytes <n>    skip files larger default 50_000_000
 *
 * Staging layout: {staging}/{hash-prefix-2}/{sha256}.{ext-from-content-type}
 * Hash = stable identity: a slot rename (promote.mjs) never re-downloads.
 */

import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { loadPlaywright } from "./lib/playwright-loader.mjs";

const EXT_FROM_TYPE = {
  "image/jpeg": "jpg",
  "image/png": "png",
  "image/webp": "webp",
  "image/gif": "gif",
  "image/avif": "avif",
  "image/svg+xml": "svg",
  "video/mp4": "mp4",
  "video/webm": "webm",
  "audio/mpeg": "mp3",
  "audio/mp4": "m4a",
  "audio/ogg": "ogg",
  "audio/wav": "wav",
  "font/woff2": "woff2",
  "font/woff": "woff",
  "application/json": "json",
};

function parseArgs(argv) {
  const out = { outDir: "_webclone/captures", stagingDir: "_webclone/staging", maxBytes: 50_000_000 };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--help" || arg === "-h") out.help = true;
    else if (arg === "--out") out.outDir = argv[++i] || out.outDir;
    else if (arg === "--staging") out.stagingDir = argv[++i] || out.stagingDir;
    else if (arg === "--max-bytes") out.maxBytes = Number(argv[++i] || "50000000");
    else throw new Error(`Unexpected argument: ${arg}`);
  }
  return out;
}

function extFor(url, contentType) {
  const fromType = EXT_FROM_TYPE[(contentType || "").split(";")[0].trim().toLowerCase()];
  if (fromType) return fromType;
  const fromUrl = path.extname(new URL(url).pathname).replace(".", "").toLowerCase();
  return /^(png|jpe?g|webp|gif|avif|svg|mp4|webm|mov|mp3|ogg|wav|m4a|woff2?|ttf|otf|json)$/.test(fromUrl) ? fromUrl.replace("jpeg", "jpg") : "bin";
}

function formatBytes(bytes) {
  if (!bytes) return "?";
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(0)} KB`;
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
}

function indexRow(item) {
  const dom = item.dom;
  const name = dom?.alt || dom?.family || path.basename(new URL(item.url).pathname).slice(0, 40) || item.kind;
  const size = dom?.naturalW ? `${dom.naturalW}×${dom.naturalH}` : "";
  const where = dom ? `${dom.tag}${dom.inSection ? ` @ ${dom.inSection}` : ""}` : "network-only";
  return `| ${name} | ${item.kind} | ${where} | ${size} | ${item.states.join(", ")} | ${item.hash ? `${item.hash.slice(0, 10)} · ${formatBytes(item.bytes)}` : "FAILED"} |`;
}

function writeIndex(outDir, routes, stats) {
  const lines = [
    "# Media index — raw evidence (staging)",
    "",
    `> Auto-generated by download.mjs. Semantic slot names are assigned in Phase 2 and materialize in`,
    `> \`public/clone-assets/\` via promote.mjs — this file lists EVERYTHING harvested (capture-all, R4).`,
    `> Cross-route duplicates share one hash. \`${stats.uniqueHashes}\` unique file(s), ${stats.failed} failed.`,
    "",
    `| Kind | Items | Unique files | Bytes (unique) |`,
    `|---|---:|---:|---:|`,
  ];
  for (const [kind, value] of Object.entries(stats.kinds)) {
    lines.push(`| ${kind} | ${value.items} | ${value.unique} | ${formatBytes(value.bytes)} |`);
  }
  lines.push("");
  for (const route of routes) {
    lines.push(`## ${route.slug} — \`${route.path}\``);
    lines.push("");
    lines.push(`| What | Kind | Where (DOM) | Natural | States | Hash · size |`);
    lines.push(`|---|---|---|---|---|---|`);
    for (const item of route.items) lines.push(indexRow(item));
    lines.push("");
  }
  fs.writeFileSync(path.join(outDir, "media-index.md"), `${lines.join("\n")}\n`);
}

// ---------------------------------------------------------------------------
async function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.help) {
    console.log("node .claude/skills/web-clone/scripts/download.mjs [--out dir] [--staging dir] [--max-bytes n]");
    return;
  }
  const outDir = path.resolve(args.outDir);
  const stagingDir = path.resolve(args.stagingDir);

  const manifests = fs
    .readdirSync(outDir)
    .filter((entry) => fs.statSync(path.join(outDir, entry)).isDirectory())
    .map((slug) => path.join(outDir, slug, "media.json"))
    .filter((file) => fs.existsSync(file))
    .map((file) => JSON.parse(fs.readFileSync(file, "utf8")));
  if (manifests.length === 0) {
    throw new Error(`No media.json under ${outDir} — run orchestrator.mjs first`);
  }

  const storageStatePath = path.join(outDir, "storage-state.json");
  // Standalone APIRequestContext — no browser needed, cookies ride from storageState.
  const playwright = loadPlaywright();
  const request = await playwright.request.newContext(fs.existsSync(storageStatePath) ? { storageState: storageStatePath } : {});

  const hashToPath = new Map(); // sha256 -> staging path (dedup across ALL routes)
  const urlToHash = new Map();
  let failed = 0;

  for (const manifest of manifests) {
    for (const item of manifest.items) {
      if (item.hash) continue; // already staged (rerun after partial failure)
      if (item.url.startsWith("data:") || item.url.startsWith("inline-svg:")) {
        item.hash = "skipped:" + item.url.slice(0, 24);
        item.localPath = "";
        continue;
      }
      try {
        const cached = urlToHash.get(item.url);
        let filePath = cached ? hashToPath.get(cached) : null;
        let buffer;
        let contentType;
        if (filePath && fs.existsSync(filePath)) {
          buffer = fs.readFileSync(filePath);
          contentType = item.contentType || "application/octet-stream";
        } else {
          const response = await request.get(item.url, { timeout: 30_000, maxRedirects: 4 });
          if (!response.ok()) throw new Error(`HTTP ${response.status()}`);
          buffer = Buffer.from(await response.body());
          contentType = response.headers()["content-type"] || "";
          if (buffer.length > args.maxBytes) throw new Error(`too large: ${buffer.length}`);
        }
        const hash = crypto.createHash("sha256").update(buffer).digest("hex");
        if (!hashToPath.has(hash)) {
          filePath = path.join(stagingDir, hash.slice(0, 2), `${hash}.${extFor(item.url, contentType)}`);
          fs.mkdirSync(path.dirname(filePath), { recursive: true });
          fs.writeFileSync(filePath, buffer);
          hashToPath.set(hash, filePath);
        } else {
          filePath = hashToPath.get(hash);
        }
        urlToHash.set(item.url, hash);
        item.hash = hash;
        item.localPath = path.relative(".", filePath).replaceAll("\\", "/");
        item.bytes = buffer.length;
        item.contentType = contentType.split(";")[0];
      } catch (error) {
        failed += 1;
        item.downloadError = error.message;
        console.error(`FAIL  ${item.url} — ${error.message}`);
      }
    }
    fs.writeFileSync(path.join(outDir, manifest.route, "media.json"), `${JSON.stringify(manifest, null, 2)}\n`);
  }

  const stats = { uniqueHashes: hashToPath.size, failed, kinds: {} };
  for (const manifest of manifests) {
    for (const item of manifest.items) {
      const bucket = (stats.kinds[item.kind] ||= { items: 0, unique: 0, bytes: 0 });
      bucket.items += 1;
      if (item.hash && hashToPath.has(item.hash) && !(manifest._seen ||= new Set()).has(item.hash)) {
        manifest._seen.add(item.hash);
        bucket.unique += 1;
        bucket.bytes += item.bytes || 0;
      }
    }
  }
  await request.dispose();
  writeIndex(outDir, manifests, stats);
  console.log(`Staged ${hashToPath.size} unique file(s) → ${args.stagingDir} · ${failed} failure(s) · index → ${path.join(outDir, "media-index.md")}`);
  if (failed > 0) process.exitCode = 1;
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
